project_id = "fpjzrijdruoknalrqcrt"

[functions.create-pix]
verify_jwt = false

[functions.mistic-webhook]
verify_jwt = false

[functions.backfill-payments]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false
 
 [functions.generate-ebook]
 verify_jwt = false
 
 [functions.send-lead-email]
 verify_jwt = false
