project_id = "fpjzrijdruoknalrqcrt"

[functions.create-pix]
verify_jwt = false

[functions.pushinpay-webhook]
verify_jwt = false

[functions.backfill-payments]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false